backend:
  name: github
  repo: anhhangxomfoto/anhhangxomfoto.github.io
  branch: anhnnt-master 
  site_domain: phenomenal-lolly-bbed3e.netlify.app
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"
# Cấu hình lưu trữ hình ảnh
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Tắt tính năng xem trước (Live Preview) vì nó hay bị vỡ layout với Jekyll Liquid
editor:
  preview: false

collections:
  - name: "posts"
    label: "Bài Viết"
    folder: "_posts"
    create: true
    path: "{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    # BẮT BUỘC CHO JEKYLL: Định dạng tên tệp phải có ngày tháng
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Tác giả", name: "author", widget: "string", default: "sal"}
      - {label: "Chế độ tải ảnh", name: "lazyimages", widget: "hidden", default: "enabled"}
      - {label: "Chuyên mục", name: "categories", widget: "list", default: ["Sức khỏe 💪"]}
      - {label: "Từ khóa (Tags)", name: "tags", widget: "list"}
      - {label: "Ảnh đại diện", name: "image", widget: "image", default: "assets/images/2025/neewer-q120-avt.webp", required: false}
      - {label: "Đánh giá sao", name: "rating", widget: "number", value_type: "float", required: false}
      - {label: "Bình luận", name: "comments", widget: "boolean", default: true}
      - {label: "Đoạn trích dẫn", name: "excerpt", widget: "text", required: false}
      - {label: "Nội dung bài viết", name: "body", widget: "markdown"}