backend:
  name: github
  repo: anhhangxomfoto/anhhangxomfoto.github.io
  branch: anhnnt-master 
  base_url: [https://phenomenal-lolly-bbed3e.netlify.app](https://phenomenal-lolly-bbed3e.netlify.app)

# Cấu hình lưu trữ hình ảnh
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Tắt tính năng xem trước (Live Preview) vì nó hay bị vỡ layout với Jekyll Liquid
editor:
  preview: false

collections:
  - name: "posts"
    label: "Bài Viết"
    folder: "_posts"
    create: true
    # BẮT BUỘC CHO JEKYLL: Định dạng tên tệp phải có ngày tháng
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Trường ẩn này tự động chèn 'layout: post' vào bài viết mới
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
