- name: Publish Sitemap
        env:
          GOOGLE_SEARCH_CONSOLE_JSON_KEY: ${{ secrets.GOOGLE_SEARCH_CONSOLE_JSON_KEY }}
        run: |
          # node path/to/your-script.js
          # Hoặc nếu là chạy tệp bash:
          bash ./scripts/publish_sitemap/publish.sh